
get http://localhost:3001/api/users/5de432b176549f2f9480b63f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNwbGFzaG1hbiIsImlkIjoiNWRlNDMxNmU3NjU0OWYyZjk0ODBiNjNkIiwiaWF0IjoxNTc1MjM3MjY5fQ.qIsJmcGGzWkXSRaTTWw_lLArGEn7Z7I_DPraN6MChkI