get http://localhost:3001/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNwbGFzaG1hbiIsImlkIjoiNWRiZjYwYjBiODFhY2M2ZTY4ZjllOTVkIiwiaWF0IjoxNTcyODM5OTM1fQ.f4OAuQbPPc92Rqe-cxTUyPmtBYO7jnLW_ZV8Y145g-E